---
parameters:
  ui_config:
    name: ui5
    full_name: UI5
    protocol: http
    upload_path: '%kernel.project_dir%/public/uploads'
    filters:
      multiple: true
      settings: ~
    entity:
      App\Entity\Page:
        name: App\Entity\Page
        table_name: page
        name_field: name
        order_by: id
        order_dir: desc
        is_tree: true
        form:
          translations:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: Uicms\Admin\Form\DataTransformer\DefaultTransformer
              options:
                required: true
            html:
              name: Html
              type: TextareaType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: false
                attr:
                  class: tinymce
          fields:
            controller:
              name: Controller
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: true
            action:
              name: Action
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: false
            template:
              name: Template
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: false
            menu:
              name: Menu
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: false
            slug:
              name: Slug
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              modifier: Uicms\Admin\Form\DataModifier\SlugModifier
              transformer: ~
              options:
                required: false
            helper:
              name: Helper
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
            class:
              name: Class
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
      App\Entity\User:
        name: App\Entity\User
        table_name: user
        name_field: email
        order_by: id
        order_dir: desc
        form:
          translations: ~
          fields:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: true
            email:
              name: Email
              type: EmailType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                required: true
            plain_password:
              name: PlainPassword
              type: RepeatedType
              dest: Password
              namespace: Symfony\Component\Form\Extension\Core\Type
              options:
                attr:
                  class: repeatedType
                required: false
                type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                translation_domain: admin
                label: fld_user_password
                first_options:
                  label: fld_user_new_password
                second_options:
                  label: fld_user_repeat_password
            roles:
              name: Roles
              type: CollectionType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ~
              options:
                attr:
                  class: collectionType
                required: true
                allow_add: true
                allow_delete: true
      App\Entity\Media:
        table_name: media
        name: App\Entity\Media
        name_field: name
        is_tree: "1"
        order_by: id
        order_dir: desc
        form:
          class: App\Entity\Media
          translations:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              public: true
              public_required: true
              options:
                help: ""
                label: fld_media_name
                attr:
                  class: ""
                required: true
            description:
              name: Description
              type: TextareaType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              public: true
              public_required: true
              options:
                help: ""
                label: fld_media_description
                attr:
                  class: tinymce
                required: false
          fields:
            file:
              name: File
              type: UIFileType
              namespace: Uicms\Admin\Form\Type
              transformer: Uicms\Admin\Form\DataTransformer\FileTransformer
              public: true
              public_required: true
              options:
                help: ""
                label: fld_media_file
                attr:
                  class: ""
                required: false
                template: file
            class:
              name: Class
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: fld_media_class
                attr:
                  class: ""
                required: false
      App\Entity\Block:
        table_name: block
        name: App\Entity\Block
        name_field: name
        is_tree: "1"
        order_by: id
        order_dir: desc
        form:
          class: App\Entity\Block
          translations:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
            text:
              name: Text
              type: TextareaType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: tinymce
                required: false
          fields:
            template:
              name: Template
              type: ChoiceType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
                choices:
                  Texte / medias: default
                  Collection: collection
                  Carte: map
            style:
              name: Style
              type: ChoiceType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
                choices:
                  Titre: title
                  Chapo: chapo
                  Texte: text
                  Couverture: cover
                  Planche contact: medias_grid
                  "Medias \xE0 gauche": medias_left
                  "Medias \xE0 droite": medias_right
                  "Accord\xE9on": accordion
            class:
              name: Class
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
            block_collection:
              name: BlockCollection
              type: EntityType
              namespace: Symfony\Bridge\Doctrine\Form\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
                choice_label: translations[fr].name
                class: App\Entity\BlockCollection
            slug:
              name: Slug
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
      App\Entity\BlockCollection:
        table_name: block_collection
        name: App\Entity\BlockCollection
        name_field: name
        is_tree: 0
        order_by: id
        order_dir: desc
        form:
          class: App\Entity\BlockCollection
          translations:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
          fields:
            entity:
              name: Entity
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
      App\Entity\Param:
        table_name: param
        name: App\Entity\Param
        name_field: name
        is_tree: 0
        order_by: id
        order_dir: desc
        form:
          class: App\Entity\Param
          translations:
            value:
              name: Value
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
          fields:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
      App\Entity\Email:
        table_name: email
        name: App\Entity\Email
        name_field: name
        is_tree: 0
        order_by: id
        order_dir: desc
        form:
          class: App\Entity\Email
          translations:
            name:
              name: Name
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: Sujet de l'email
                attr:
                  class: ""
                required: false
            text:
              name: Text
              type: TextareaType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: Message
                attr:
                  class: tinymce
                required: false
          fields:
            slug:
              name: Slug
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
            from:
              name: From
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
            from_label:
              name: FromLabel
              type: TextType
              namespace: Symfony\Component\Form\Extension\Core\Type
              transformer: ""
              options:
                help: ""
                label: ""
                attr:
                  class: ""
                required: false
      App\Entity\LinkBlockCollectionPage:
        table_name: link_block_collection_page
        name: App\Entity\Page
        name_field: id
        order_by: id
        order_dir: desc
        link:
        - App\Entity\BlockCollection
        - App\Entity\Page
      App\Entity\LinkPageBlock:
        table_name: link_page_block
        name: App\Entity\Block
        name_field: id
        order_by: id
        order_dir: desc
        link:
        - App\Entity\Page
        - App\Entity\Block
      App\Entity\LinkBlockMedia:
        table_name: link_block_media
        name: App\Entity\Media
        name_field: id
        order_by: id
        order_dir: desc
        link:
        - App\Entity\Block
        - App\Entity\Media
      App\Entity\LinkPageMedia:
        table_name: link_page_media
        name: App\Entity\Media
        name_field: id
        order_by: id
        order_dir: desc
        link:
        - App\Entity\Page
        - App\Entity\Media
    admin:
      vars:
        limit: 50
        offset: 0
        order_by: id
        order_dir: desc
        linked_to: ~
        linked_to_id: []
        linked_to_slug: ~
        display: list
        parent: ~
        dir: 0
        select_action: ~
        select_field: ~
        search: ~
      pages:
        pages:
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: pages
          arguments:
            entity_name: App\Entity\Page
          params: ~
        blocks:
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: blocks
          arguments:
            entity_name: App\Entity\Block
          params: []
        block_collections:
          display: false
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: block_collections
          arguments:
            entity_name: App\Entity\BlockCollection
          params: []
        medias:
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: medias
          arguments:
            entity_name: App\Entity\Media
          params:
            display: thumbnails
        params:
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: params
          arguments:
            entity_name: App\Entity\Param
          displayed_fields:
          - value
          params: []
        emails:
          display: false
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: emails
          arguments:
            entity_name: App\Entity\Email
          params: []
          displayed_fields:
          - slug
        action:
          controller: Uicms\Admin\Controller\Action
          action: index
          slug: action
          display: false
          params: ~
        users:
          controller: Uicms\Admin\Controller\Editor
          action: index
          slug: users
          is_tree: false
          arguments:
            entity_name: App\Entity\User
          params: ~
        
...
