admin:
    path: /admin/
    defaults: { _controller: 'Uicms\Admin\Controller\IndexController::index' }

admin_login:
    path: /admin/login
    defaults: { _controller: 'Uicms\Admin\Controller\SecurityController::login' }

admin_logout:
    path: /admin/logout
    defaults: { _controller: 'Uicms\Admin\Controller\SecurityController::logout' }
    
admin_page:
    path: /admin/{slug}
    defaults: { _controller: 'Uicms\Admin\Controller\IndexController::index' }

admin_page_action:
    path: /admin/{slug}/{action}
    defaults: { _controller: 'Uicms\Admin\Controller\IndexController::index' }

admin_page_action_id:
    path: /admin/{slug}/{action}/{id}
    defaults: { _controller: 'Uicms\Admin\Controller\IndexController::index' }

app:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::index', locale: '%locale%' }

app_lang:
    path: /{locale}
    defaults: { _controller: 'App\Controller\IndexController::index'}

app_page:
    path: /{locale}/{slug}
    defaults: { _controller: 'App\Controller\IndexController::index'}

app_page_action:
    path: /{locale}/{slug}/{action}
    defaults: { _controller: 'App\Controller\IndexController::index'}

app_page_id_key:
    path: /{locale}/{slug}/{id}/{key}
    defaults: { _controller: 'App\Controller\IndexController::index', action: 'index'}

app_page_action_id_key:
    path: /{locale}/{slug}/{action}/{id}/{key}
    defaults: { _controller: 'App\Controller\IndexController::index'}
    